global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-profile'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-profile:8080']
  
  - job_name: 'movie-catalog'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['movie-catalog:8080']
