apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql/
  - redis/
  - kafka/
  - elasticsearch/
  - kibana/
  - minio/

namespace: default

labels:
  - pairs:
      environment: development
      project: movie-rating-service