apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:9.1.5
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
      volumes:
        - name: kibana-data
          persistentVolumeClaim:
            claimName: kibana-pvc